# locals are used to define values that are used in multiple places in the configuration file
locals {
  default_location = "West Europe"
}

/*
  The output block defines values that are output by the module. 
  These values can be used by other configurations to access the values that are generated by the module.
*/
output "location" {
  value = local.default_location
}